### ISSUE TITLE
save data (state restore) - how does it work?

### ISSUE THREAD

**Issue by marcushultman** [jgilchrist/gbemu#12]
Hi! Great emulator, I got a custom `Gameboy` instance working very quickly in my environment. However, I think I am struggling with state restore/save data. I'm saving the `get_cartridge_ram()` to disk and pass it as `save_data` [in the ctor](https://github.com/jgilchrist/gbemu/blob/master/src/gameboy.h#L22), but the game I'm trying out is always starting from the beginning. I've tried saving both during the `run`-loop and afterwards, and data seem to be written (there is binary data in the file). Am I misunderstanding something, or is it maybe the ROM I'm using that is to blame?

**Comment by jgilchrist** [comment]
Great choice 😁

No, currently no internal state is saved - there are other emulators that 'snapshot' the internal state of the emulator (registers, internal memory, etc.) and allow you to return to the exact state of the emulator from that snapshot, but I haven't got round to implementing that yet.

The saving that is implemented here is closer to saving on the original Gameboy - that is, it only saves the state of the cartridge RAM. For example, if you were to go into the save menu in Pokemon and save the game, you should see that the saved game data is persisted if you close and re-open the emulator (i.e. you will see 'Continue' in the main menu) - that is because the cartridge RAM data is persisted via the code in the file I linked above. This simulates the battery in the real cartridges keeping the cartridge RAM data even when the Gameboy itself is switched on and off, clearing the Gameboy's internal memory.

**Comment by marcushultman** [comment]
Ah, cool then I think I understand what to expect better! 🙏🏻
